version: "3.8"
services:
    web-server:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        # depends_on:
        #     - db
        image: php:7.4-apache
        restart: always
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80

    # db:
    #     container_name: mysql
    #     image: mysql
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_USER: ${DB_USERNAME}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #     ports:
    #         - "3306:3306"

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - "8080:80"
    #     restart: always
    #     environment:
    #         PMA_HOST: db
    #     depends_on:
    #         - db